#!/usr/bin/env python3
from __future__ import annotations

from functools import lru_cache
from pathlib import Path
from urllib.parse import quote


BOOK_EXTENSIONS = {
    ".azw",
    ".azw3",
    ".djvu",
    ".epub",
    ".mobi",
    ".pdf",
}
TREE_EXTENSIONS = BOOK_EXTENSIONS | {
    ".jpeg",
    ".jpg",
    ".png",
}
IGNORE_NAMES = {
    ".git",
    ".github",
    ".DS_Store",
    "FILE_INDEX.md",
    "README.md",
    "auto_update-readme-tree.yml",
    "auto_update_readme_tree.py",
    "__pycache__",
    "scripts",
}
TREE_IGNORE_NAMES = IGNORE_NAMES | {"speaches"}
INDEX_EXTENSIONS = BOOK_EXTENSIONS | {
    ".jpeg",
    ".jpg",
    ".md",
    ".png",
}
START_MARKER = "<!-- file-tree:start -->"
END_MARKER = "<!-- file-tree:end -->"

REPO_ROOT = Path(__file__).resolve().parent
README_PATH = REPO_ROOT / "README.md"
FILE_INDEX_PATH = REPO_ROOT / "FILE_INDEX.md"


def is_book_file(path: Path) -> bool:
    return path.is_file() and path.suffix.lower() in BOOK_EXTENSIONS


def is_tree_file(path: Path) -> bool:
    return path.is_file() and path.suffix.lower() in TREE_EXTENSIONS


def is_indexed_file(path: Path) -> bool:
    return path.is_file() and path.suffix.lower() in INDEX_EXTENSIONS


@lru_cache(maxsize=None)
def directory_has_books(directory: Path) -> bool:
    for entry in directory.iterdir():
        if should_ignore_tree(entry):
            continue
        if is_tree_file(entry):
            return True
        if entry.is_dir() and directory_has_books(entry):
            return True
    return False


def should_ignore(path: Path) -> bool:
    return path.name.startswith(".") or path.name in IGNORE_NAMES


def should_ignore_tree(path: Path) -> bool:
    return path.name.startswith(".") or path.name in TREE_IGNORE_NAMES


def included_entries(directory: Path) -> list[Path]:
    directories: list[Path] = []
    files: list[Path] = []

    for entry in sorted(directory.iterdir(), key=lambda item: item.name.lower()):
        if should_ignore_tree(entry):
            continue
        if entry.is_dir() and directory_has_books(entry):
            directories.append(entry)
        elif is_tree_file(entry):
            files.append(entry)

    return directories + files


def render_tree(root: Path) -> str:
    lines = [f"{root.name}/"]

    def walk(directory: Path, prefix: str) -> None:
        entries = included_entries(directory)
        for index, entry in enumerate(entries):
            is_last = index == len(entries) - 1
            connector = "└── " if is_last else "├── "
            suffix = "/" if entry.is_dir() else ""
            lines.append(f"{prefix}{connector}{entry.name}{suffix}")
            if entry.is_dir():
                child_prefix = f"{prefix}{'    ' if is_last else '│   '}"
                walk(entry, child_prefix)

    walk(root, "")
    return "\n".join(lines)


def indexed_files(root: Path) -> list[Path]:
    files: list[Path] = []

    def walk(directory: Path) -> None:
        for entry in sorted(directory.iterdir(), key=lambda item: item.name.lower()):
            if should_ignore(entry):
                continue
            if entry.is_dir():
                walk(entry)
            elif is_indexed_file(entry):
                files.append(entry)

    walk(root)
    files.sort(
        key=lambda path: (
            path.relative_to(root).parent.as_posix().lower(),
            path.name.lower(),
        )
    )
    return files


def render_file_index(root: Path) -> str:
    files = indexed_files(root)
    counts: dict[str, int] = {}
    for file_path in files:
        extension = file_path.suffix.lower().lstrip(".")
        counts[extension] = counts.get(extension, 0) + 1

    summary = ", ".join(
        f"{count} .{extension}" for extension, count in sorted(counts.items())
    )
    lines = [
        "# File Index",
        "",
        "<!-- This file is generated by auto_update_readme_tree.py. -->",
        "",
        f"Total indexed files: {len(files)}",
        "",
        f"By type: {summary}",
        "",
        "## Files",
        "",
    ]

    current_directory: Path | None = None
    for file_path in files:
        relative_path = file_path.relative_to(root)
        directory = relative_path.parent
        if directory != current_directory:
            if current_directory is not None:
                lines.append("")
            current_directory = directory
            heading = "." if directory == Path(".") else directory.as_posix()
            lines.extend([f"### {heading}", ""])

        href = quote(relative_path.as_posix())
        lines.append(f"- [{relative_path.name}]({href})")

    lines.append("")
    return "\n".join(lines)


def update_readme() -> None:
    readme = README_PATH.read_text()
    if START_MARKER not in readme or END_MARKER not in readme:
        raise RuntimeError("README.md is missing tree markers.")

    start_index = readme.index(START_MARKER) + len(START_MARKER)
    end_index = readme.index(END_MARKER)
    tree_block = f"\n```text\n{render_tree(REPO_ROOT)}\n```\n"
    updated = f"{readme[:start_index]}{tree_block}{readme[end_index:]}"
    README_PATH.write_text(updated)


def update_file_index() -> None:
    FILE_INDEX_PATH.write_text(render_file_index(REPO_ROOT))


if __name__ == "__main__":
    update_readme()
    update_file_index()
